import { defaultBays } from './airports';
import type { Metar, Strip, StripsState, StripsTab } from './types';

type StripSeed = Pick<
  Strip,
  | 'id'
  | 'cs'
  | 'airline'
  | 'type'
  | 'wake'
  | 'adep'
  | 'ades'
  | 'gate'
  | 'sqkA'
  | 'proc'
  | 'procKind'
  | 'rwy'
  | 'cfl'
  | 'dir'
  | 'bay'
> &
  Partial<Strip>;

export function makeStrip(seed: StripSeed): Strip {
  return {
    sqkS: '',
    cleared: false,
    dcl: 'NONE',
    freeText: '',
    suggest: null,
    anim: false,
    xfr: null,
    fpl: null,
    ...seed,
  };
}

const METARS: Record<string, Metar> = {
  LPPT: {
    station: 'LPPT',
    obsTime: '05:00',
    raw: 'LPPT 120500Z 21008KT 180V240 9999 FEW025 SCT040 22/14 Q1017 NOSIG',
    wind: '210°/08',
    windNote: 'VRB 180–240',
    qnh: '1017',
    qnhAlt: '30.03 inHg',
    temp: '22 / 14',
    hum: 'RH 61%',
    vis: '10+',
    visUnit: 'km',
    ceil: 'FEW 025',
    ceilUnit: 'no ceiling',
    visM: 10000,
    ceilFt: 99999,
    rwys: ['21'],
    atis: 'K',
    depFreq: '121.750',
    clrNote: 'GND 121.750',
  },
  LPPR: {
    station: 'LPPR',
    obsTime: '05:00',
    raw: 'LPPR 120500Z 31009KT 4000 -RA BR BKN008 OVC020 17/15 Q1014 BECMG 6000',
    wind: '310°/09',
    windNote: 'steady',
    qnh: '1014',
    qnhAlt: '29.94 inHg',
    temp: '17 / 15',
    hum: 'RH 88%',
    vis: '4.0',
    visUnit: 'km · -RA BR',
    ceil: 'BKN 008',
    ceilUnit: 'ft ×100',
    visM: 4000,
    ceilFt: 800,
    rwys: ['35'],
    atis: 'F',
    depFreq: '118.000',
    clrNote: 'TWR 118.000',
  },
  LPFR: {
    station: 'LPFR',
    obsTime: '05:00',
    raw: 'LPFR 120500Z 10012KT CAVOK 24/17 Q1018',
    wind: '100°/12',
    windNote: 'steady',
    qnh: '1018',
    qnhAlt: '30.06 inHg',
    temp: '24 / 17',
    hum: 'RH 65%',
    vis: '10+',
    visUnit: 'km · CAVOK',
    ceil: 'CAVOK',
    ceilUnit: '',
    visM: 10000,
    ceilFt: 99999,
    rwys: ['10'],
    atis: 'D',
    depFreq: '118.575',
    clrNote: 'TWR 118.575',
  },
  LPMA: {
    station: 'LPMA',
    obsTime: '05:00',
    raw: 'LPMA 120500Z 05016G28KT 9999 FEW020 21/16 Q1020',
    wind: '050°/16',
    windNote: 'G 28 kt',
    qnh: '1020',
    qnhAlt: '30.12 inHg',
    temp: '21 / 16',
    hum: 'RH 73%',
    vis: '10+',
    visUnit: 'km',
    ceil: 'FEW 020',
    ceilUnit: 'no ceiling',
    visM: 10000,
    ceilFt: 99999,
    rwys: ['05'],
    atis: 'H',
    depFreq: '118.350',
    clrNote: 'TWR 118.350',
  },
  LPBJ: {
    station: 'LPBJ',
    obsTime: '05:00',
    raw: 'LPBJ 120500Z 27006KT CAVOK 23/12 Q1017',
    wind: '270°/06',
    windNote: 'steady',
    qnh: '1017',
    qnhAlt: '30.03 inHg',
    temp: '23 / 12',
    hum: 'RH 50%',
    vis: '10+',
    visUnit: 'km · CAVOK',
    ceil: 'CAVOK',
    ceilUnit: '',
    visM: 10000,
    ceilFt: 99999,
    rwys: ['19R'],
    atis: 'B',
    depFreq: '122.100',
    clrNote: 'TWR 122.100',
  },
};

const STRIP_SEEDS: Record<string, StripSeed[]> = {
  LPPT: [
    {
      id: 'p1',
      cs: 'TAP751',
      airline: 'TAP Air Portugal',
      type: 'A320',
      wake: 'M',
      adep: 'LPPT',
      ades: 'LFPO',
      gate: '512',
      sqkA: '2461',
      proc: 'INBOM5S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'PENDING',
    },
    {
      id: 'p2',
      cs: 'RYR2394',
      airline: 'Ryanair',
      type: 'B738',
      wake: 'M',
      adep: 'LPPT',
      ades: 'EGSS',
      gate: '218',
      sqkA: '2455',
      proc: 'NAKUV2S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'PENDING',
    },
    {
      id: 'p3',
      cs: 'CSDHS',
      airline: 'Private',
      type: 'C172',
      wake: 'L',
      adep: 'LPPT',
      ades: 'LPPT',
      gate: 'GA1',
      sqkA: '7000',
      sqkS: '7000',
      proc: 'VFR S',
      procKind: 'CIRCUIT',
      rwy: '21',
      cfl: '015',
      dir: 'VFR',
      bay: 'PENDING',
      freeText: 'Local flight, south',
    },
    {
      id: 'p4',
      cs: 'TAP1901',
      airline: 'TAP Air Portugal',
      type: 'A21N',
      wake: 'M',
      adep: 'LPPT',
      ades: 'EDDF',
      gate: '509',
      sqkA: '3726',
      proc: 'ODEMI4S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'CLEARED',
      cleared: true,
      dcl: 'ACK',
    },
    {
      id: 'p5',
      cs: 'SWR739',
      airline: 'Swiss',
      type: 'BCS3',
      wake: 'M',
      adep: 'LPPT',
      ades: 'LSZH',
      gate: '415',
      sqkA: '2436',
      sqkS: '2436',
      proc: 'INBOM5S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'PUSHBACK',
      cleared: true,
      dcl: 'ACK',
    },
    {
      id: 'p6',
      cs: 'TAP081',
      airline: 'TAP Air Portugal',
      type: 'A339',
      wake: 'H',
      adep: 'LPPT',
      ades: 'SBGR',
      gate: '601',
      sqkA: '2717',
      sqkS: '2717',
      proc: 'ODEMI4S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'TAXI',
      cleared: true,
      freeText: 'Full length req',
    },
    {
      id: 'p7',
      cs: 'THY1756',
      airline: 'Turkish Airlines',
      type: 'A21N',
      wake: 'M',
      adep: 'LPPT',
      ades: 'LTFM',
      gate: '411',
      sqkA: '2703',
      sqkS: '2703',
      proc: 'NAKUV2S',
      procKind: 'SID',
      rwy: '21',
      cfl: '060',
      dir: 'DEP',
      bay: 'RUNWAY',
      cleared: true,
    },
    {
      id: 'p8',
      cs: 'VLG8460',
      airline: 'Vueling',
      type: 'A320',
      wake: 'M',
      adep: 'LEBL',
      ades: 'LPPT',
      gate: '122',
      sqkA: '5512',
      sqkS: '5512',
      proc: 'TROIA2B',
      procKind: 'STAR',
      rwy: '21',
      cfl: '080',
      dir: 'ARR',
      bay: 'APPROACH',
    },
    {
      id: 'p9',
      cs: 'EIN486',
      airline: 'Aer Lingus',
      type: 'A20N',
      wake: 'M',
      adep: 'EIDW',
      ades: 'LPPT',
      gate: '130',
      sqkA: '5523',
      sqkS: '5523',
      proc: 'NAKUV1B',
      procKind: 'STAR',
      rwy: '21',
      cfl: '090',
      dir: 'ARR',
      bay: 'APPROACH',
      freeText: 'Reduced 180 kt',
    },
  ],
  LPPR: [
    {
      id: 'r1',
      cs: 'TAP1200',
      airline: 'TAP Express',
      type: 'E190',
      wake: 'M',
      adep: 'LPPR',
      ades: 'LPPT',
      gate: '12',
      sqkA: '2401',
      proc: 'TURON2P',
      procKind: 'SID',
      rwy: '35',
      cfl: '050',
      dir: 'DEP',
      bay: 'PENDING',
    },
    {
      id: 'r2',
      cs: 'RYR55PM',
      airline: 'Ryanair',
      type: 'B738',
      wake: 'M',
      adep: 'LPPR',
      ades: 'EGSS',
      gate: '24',
      sqkA: '2422',
      sqkS: '2422',
      proc: 'ODEGI3P',
      procKind: 'SID',
      rwy: '35',
      cfl: '050',
      dir: 'DEP',
      bay: 'CLEARED',
      cleared: true,
      dcl: 'SENT',
    },
    {
      id: 'r3',
      cs: 'WZZ1078',
      airline: 'Wizz Air',
      type: 'A321',
      wake: 'M',
      adep: 'LPPR',
      ades: 'EPKT',
      gate: '31',
      sqkA: '2455',
      sqkS: '2455',
      proc: 'ODEGI3P',
      procKind: 'SID',
      rwy: '35',
      cfl: '050',
      dir: 'DEP',
      bay: 'TAXI',
      cleared: true,
    },
    {
      id: 'r4',
      cs: 'EZY8695',
      airline: 'easyJet',
      type: 'A320',
      wake: 'M',
      adep: 'EGKK',
      ades: 'LPPR',
      gate: '22',
      sqkA: '5471',
      sqkS: '5471',
      proc: 'TURON1E',
      procKind: 'STAR',
      rwy: '35',
      cfl: '070',
      dir: 'ARR',
      bay: 'APPROACH',
      freeText: 'ILS Z 35',
    },
  ],
  LPFR: [
    {
      id: 'f1',
      cs: 'EXS452',
      airline: 'Jet2',
      type: 'B738',
      wake: 'M',
      adep: 'EGCC',
      ades: 'LPFR',
      gate: '8',
      sqkA: '5602',
      sqkS: '5602',
      proc: 'ALPOR1A',
      procKind: 'STAR',
      rwy: '10',
      cfl: '070',
      dir: 'ARR',
      bay: 'APPROACH',
    },
  ],
  LPMA: [],
  LPBJ: [],
};

/**
 * Airports outside the demo set (opened by ICAO from a live session)
 * get an empty AWOS shell — the protocol carries no weather, so the
 * panel shows placeholders instead of invented numbers.
 */
function placeholderMetar(icao: string): Metar {
  return {
    station: icao,
    obsTime: '',
    raw: '',
    wind: '',
    windNote: '',
    qnh: '—',
    qnhAlt: '',
    temp: '—',
    hum: '',
    vis: '—',
    visUnit: '',
    ceil: '—',
    ceilUnit: '',
    visM: 10000,
    ceilFt: 99999,
    rwys: [],
    atis: '—',
    depFreq: '',
    clrNote: '',
  };
}

export function makeTab(icao: string): StripsTab {
  const metar = METARS[icao] ?? placeholderMetar(icao);
  const seeds = STRIP_SEEDS[icao] ?? [];
  return {
    icao,
    metar,
    strips: seeds.map(makeStrip),
    bays: defaultBays(),
    locks: {},
    feed: [],
    archived: [],
    unseen: 0,
  };
}

export function initialStripsState(): StripsState {
  return {
    tabs: { LPPT: makeTab('LPPT'), LPPR: makeTab('LPPR') },
    tabsOrder: ['LPPT', 'LPPR'],
    activeTab: 'LPPT',
    toasts: [],
    seq: 100,
    feedOn: true,
    controllers: [],
    seenAirports: [],
  };
}
